/*
  ==============================================================================
    VultProcessor.h - JUCE wrapper for Vult DSP code
    Generated by DSPLab

    Copy this file to your JUCE project's Source folder
  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>

// Forward declare Vult DSP types - include your generated dsplab.h
struct dsplab_process_type;

class VultProcessor
{
public:
    VultProcessor();
    ~VultProcessor();

    void prepareToPlay(double sampleRate, int samplesPerBlock);
    void releaseResources();
    void processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midiMessages);

    void setParameter(int cc, float value);
    float getParameter(int cc) const;

    void noteOn(int note, int velocity, int channel);
    void noteOff(int note, int channel);

    void reset();

private:
    double m_sampleRate;
    dsplab_process_type m_data;
    float m_ccValues[128];
};
